### ISSUE TITLE
Refactor `ulauncher` package

### ISSUE THREAD

**Issue by gornostal** [gornostal/ulauncher#33]
TODO:
* get rid of `backend`
* everything that has to do with user applications and search for them has to be in one namespace

**Comment by yatsenko** [comment]
first suggestion: it's better to store py files with all windows classes in one package

**Comment by yatsenko** [comment]
why do we have some py files for rendering windows in ulauncher dir and another in ulauncher_lib ))

**Comment by yatsenko** [comment]
can we move PreferencesDialog.py, AboutDialog.py, Window.py from ulauncher_lib into ulauncher ? then we can put all these classes into some package "ui", "views", "windows" etc

**Comment by gornostal** [comment]
Good ideas. I hope I'll have time tomorrow to think about this.

**Comment by gornostal** [comment]
> why do we have some py files for rendering windows in ulauncher dir and another in ulauncher_lib ))

That's how `quickly` created application structure. AboutDialog.py is a base class for AboutUlauncherDialog.py, so I see why it's in ulauncher_lib.

**Comment by gornostal** [comment]
This issue was moved to Ulauncher/Ulauncher#6
